version: "3.8"

services:
  db:
    image: postgres:16
    container_name: agendamentos_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: agendamentos
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
